# coding: utf-8

"""
    EnduroSat SpaceOps REST API

    Documentation for EnduroSat SpaceOps REST API  # noqa: E501

    The version of the OpenAPI document: 0.34.7
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from endurosat_api.configuration import Configuration


class AccessControlPolicy(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'description': 'str',
        'actions': 'list[str]',
        'resources': 'list[dict(str, str)]',
        'principals': 'list[dict(str, str)]'
    }

    attribute_map = {
        'description': 'description',
        'actions': 'actions',
        'resources': 'resources',
        'principals': 'principals'
    }

    def __init__(self, description=None, actions=None, resources=None, principals=None, local_vars_configuration=None):  # noqa: E501
        """AccessControlPolicy - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._description = None
        self._actions = None
        self._resources = None
        self._principals = None
        self.discriminator = None

        if description is not None:
            self.description = description
        if actions is not None:
            self.actions = actions
        if resources is not None:
            self.resources = resources
        if principals is not None:
            self.principals = principals

    @property
    def description(self):
        """Gets the description of this AccessControlPolicy.  # noqa: E501


        :return: The description of this AccessControlPolicy.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this AccessControlPolicy.


        :param description: The description of this AccessControlPolicy.  # noqa: E501
        :type description: str
        """

        self._description = description

    @property
    def actions(self):
        """Gets the actions of this AccessControlPolicy.  # noqa: E501


        :return: The actions of this AccessControlPolicy.  # noqa: E501
        :rtype: list[str]
        """
        return self._actions

    @actions.setter
    def actions(self, actions):
        """Sets the actions of this AccessControlPolicy.


        :param actions: The actions of this AccessControlPolicy.  # noqa: E501
        :type actions: list[str]
        """

        self._actions = actions

    @property
    def resources(self):
        """Gets the resources of this AccessControlPolicy.  # noqa: E501


        :return: The resources of this AccessControlPolicy.  # noqa: E501
        :rtype: list[dict(str, str)]
        """
        return self._resources

    @resources.setter
    def resources(self, resources):
        """Sets the resources of this AccessControlPolicy.


        :param resources: The resources of this AccessControlPolicy.  # noqa: E501
        :type resources: list[dict(str, str)]
        """

        self._resources = resources

    @property
    def principals(self):
        """Gets the principals of this AccessControlPolicy.  # noqa: E501


        :return: The principals of this AccessControlPolicy.  # noqa: E501
        :rtype: list[dict(str, str)]
        """
        return self._principals

    @principals.setter
    def principals(self, principals):
        """Sets the principals of this AccessControlPolicy.


        :param principals: The principals of this AccessControlPolicy.  # noqa: E501
        :type principals: list[dict(str, str)]
        """

        self._principals = principals

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AccessControlPolicy):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, AccessControlPolicy):
            return True

        return self.to_dict() != other.to_dict()
