# coding: utf-8

"""
    EnduroSat SpaceOps REST API

    Documentation for EnduroSat SpaceOps REST API  # noqa: E501

    The version of the OpenAPI document: 0.34.7
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from endurosat_api.configuration import Configuration


class CommunicationProtocol(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'type': 'str',
        'satellite_streams': 'dict(str, str)',
        'user_streams': 'dict(str, str)',
        'configuration': 'dict(str, str)'
    }

    attribute_map = {
        'type': 'type',
        'satellite_streams': 'satelliteStreams',
        'user_streams': 'userStreams',
        'configuration': 'configuration'
    }

    def __init__(self, type=None, satellite_streams=None, user_streams=None, configuration=None, local_vars_configuration=None):  # noqa: E501
        """CommunicationProtocol - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._type = None
        self._satellite_streams = None
        self._user_streams = None
        self._configuration = None
        self.discriminator = None

        if type is not None:
            self.type = type
        if satellite_streams is not None:
            self.satellite_streams = satellite_streams
        if user_streams is not None:
            self.user_streams = user_streams
        if configuration is not None:
            self.configuration = configuration

    @property
    def type(self):
        """Gets the type of this CommunicationProtocol.  # noqa: E501

        Type of the communication protocol  # noqa: E501

        :return: The type of this CommunicationProtocol.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this CommunicationProtocol.

        Type of the communication protocol  # noqa: E501

        :param type: The type of this CommunicationProtocol.  # noqa: E501
        :type type: str
        """

        self._type = type

    @property
    def satellite_streams(self):
        """Gets the satellite_streams of this CommunicationProtocol.  # noqa: E501

        Describes streams between satellites and the ground station  # noqa: E501

        :return: The satellite_streams of this CommunicationProtocol.  # noqa: E501
        :rtype: dict(str, str)
        """
        return self._satellite_streams

    @satellite_streams.setter
    def satellite_streams(self, satellite_streams):
        """Sets the satellite_streams of this CommunicationProtocol.

        Describes streams between satellites and the ground station  # noqa: E501

        :param satellite_streams: The satellite_streams of this CommunicationProtocol.  # noqa: E501
        :type satellite_streams: dict(str, str)
        """

        self._satellite_streams = satellite_streams

    @property
    def user_streams(self):
        """Gets the user_streams of this CommunicationProtocol.  # noqa: E501

        Describes streams between the ground station and the Cloud layer  # noqa: E501

        :return: The user_streams of this CommunicationProtocol.  # noqa: E501
        :rtype: dict(str, str)
        """
        return self._user_streams

    @user_streams.setter
    def user_streams(self, user_streams):
        """Sets the user_streams of this CommunicationProtocol.

        Describes streams between the ground station and the Cloud layer  # noqa: E501

        :param user_streams: The user_streams of this CommunicationProtocol.  # noqa: E501
        :type user_streams: dict(str, str)
        """

        self._user_streams = user_streams

    @property
    def configuration(self):
        """Gets the configuration of this CommunicationProtocol.  # noqa: E501

        Antenna Configuration Properties as supported by EnduroSat  # noqa: E501

        :return: The configuration of this CommunicationProtocol.  # noqa: E501
        :rtype: dict(str, str)
        """
        return self._configuration

    @configuration.setter
    def configuration(self, configuration):
        """Sets the configuration of this CommunicationProtocol.

        Antenna Configuration Properties as supported by EnduroSat  # noqa: E501

        :param configuration: The configuration of this CommunicationProtocol.  # noqa: E501
        :type configuration: dict(str, str)
        """

        self._configuration = configuration

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CommunicationProtocol):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, CommunicationProtocol):
            return True

        return self.to_dict() != other.to_dict()
