# coding: utf-8

"""
    EnduroSat SpaceOps REST API

    Documentation for EnduroSat SpaceOps REST API  # noqa: E501

    The version of the OpenAPI document: 0.34.7
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from endurosat_api.configuration import Configuration


class ExecutionRule(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'execution_rule_type': 'str',
        'properties': 'dict(str, str)'
    }

    attribute_map = {
        'execution_rule_type': 'executionRuleType',
        'properties': 'properties'
    }

    def __init__(self, execution_rule_type=None, properties=None, local_vars_configuration=None):  # noqa: E501
        """ExecutionRule - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._execution_rule_type = None
        self._properties = None
        self.discriminator = None

        if execution_rule_type is not None:
            self.execution_rule_type = execution_rule_type
        if properties is not None:
            self.properties = properties

    @property
    def execution_rule_type(self):
        """Gets the execution_rule_type of this ExecutionRule.  # noqa: E501

        Execution Rule type  # noqa: E501

        :return: The execution_rule_type of this ExecutionRule.  # noqa: E501
        :rtype: str
        """
        return self._execution_rule_type

    @execution_rule_type.setter
    def execution_rule_type(self, execution_rule_type):
        """Sets the execution_rule_type of this ExecutionRule.

        Execution Rule type  # noqa: E501

        :param execution_rule_type: The execution_rule_type of this ExecutionRule.  # noqa: E501
        :type execution_rule_type: str
        """
        allowed_values = ["FIRST_OPPORTUNITY", "SPECIFIC_PASS", "SPECIFIC_GROUND_STATION", "EVERY_PASS", "EVERY_N_DAYS", "CONDITIONAL"]  # noqa: E501
        if self.local_vars_configuration.client_side_validation and execution_rule_type not in allowed_values:  # noqa: E501
            raise ValueError(
                "Invalid value for `execution_rule_type` ({0}), must be one of {1}"  # noqa: E501
                .format(execution_rule_type, allowed_values)
            )

        self._execution_rule_type = execution_rule_type

    @property
    def properties(self):
        """Gets the properties of this ExecutionRule.  # noqa: E501

        Execution Rule properties  # noqa: E501

        :return: The properties of this ExecutionRule.  # noqa: E501
        :rtype: dict(str, str)
        """
        return self._properties

    @properties.setter
    def properties(self, properties):
        """Sets the properties of this ExecutionRule.

        Execution Rule properties  # noqa: E501

        :param properties: The properties of this ExecutionRule.  # noqa: E501
        :type properties: dict(str, str)
        """

        self._properties = properties

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ExecutionRule):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ExecutionRule):
            return True

        return self.to_dict() != other.to_dict()
