# coding: utf-8

"""
    EnduroSat SpaceOps REST API

    Documentation for EnduroSat SpaceOps REST API  # noqa: E501

    The version of the OpenAPI document: 0.34.7
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from endurosat_api.configuration import Configuration


class NewDeviceMetadataType(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'device_key': 'str',
        'device_group_key': 'str'
    }

    attribute_map = {
        'device_key': 'deviceKey',
        'device_group_key': 'deviceGroupKey'
    }

    def __init__(self, device_key=None, device_group_key=None, local_vars_configuration=None):  # noqa: E501
        """NewDeviceMetadataType - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._device_key = None
        self._device_group_key = None
        self.discriminator = None

        if device_key is not None:
            self.device_key = device_key
        if device_group_key is not None:
            self.device_group_key = device_group_key

    @property
    def device_key(self):
        """Gets the device_key of this NewDeviceMetadataType.  # noqa: E501


        :return: The device_key of this NewDeviceMetadataType.  # noqa: E501
        :rtype: str
        """
        return self._device_key

    @device_key.setter
    def device_key(self, device_key):
        """Sets the device_key of this NewDeviceMetadataType.


        :param device_key: The device_key of this NewDeviceMetadataType.  # noqa: E501
        :type device_key: str
        """

        self._device_key = device_key

    @property
    def device_group_key(self):
        """Gets the device_group_key of this NewDeviceMetadataType.  # noqa: E501


        :return: The device_group_key of this NewDeviceMetadataType.  # noqa: E501
        :rtype: str
        """
        return self._device_group_key

    @device_group_key.setter
    def device_group_key(self, device_group_key):
        """Sets the device_group_key of this NewDeviceMetadataType.


        :param device_group_key: The device_group_key of this NewDeviceMetadataType.  # noqa: E501
        :type device_group_key: str
        """

        self._device_group_key = device_group_key

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, NewDeviceMetadataType):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, NewDeviceMetadataType):
            return True

        return self.to_dict() != other.to_dict()
