# coding: utf-8

"""
    EnduroSat SpaceOps REST API

    Documentation for EnduroSat SpaceOps REST API  # noqa: E501

    The version of the OpenAPI document: 0.34.7
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import endurosat_api
from endurosat_api.api.satellites_api import SatellitesApi  # noqa: E501
from endurosat_api.rest import ApiException


class TestSatellitesApi(unittest.TestCase):
    """SatellitesApi unit test stubs"""

    def setUp(self):
        self.api = endurosat_api.api.satellites_api.SatellitesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_satellite(self):
        """Test case for create_satellite

        Create a Satellite  # noqa: E501
        """
        pass

    def test_delete_satellite_by_id(self):
        """Test case for delete_satellite_by_id

        Delete a Satellite  # noqa: E501
        """
        pass

    def test_get_all_satellites(self):
        """Test case for get_all_satellites

        Get all Satellites  # noqa: E501
        """
        pass

    def test_get_satellite_by_id(self):
        """Test case for get_satellite_by_id

        Get a Satellite by ID  # noqa: E501
        """
        pass

    def test_update_satellite_by_id(self):
        """Test case for update_satellite_by_id

        Update a Satellite  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
