# coding: utf-8

"""
    EnduroSat SpaceOps REST API

    Documentation for EnduroSat SpaceOps REST API  # noqa: E501

    The version of the OpenAPI document: 0.34.7
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import endurosat_api
from endurosat_api.api.satellite_subsystems_api import SatelliteSubsystemsApi  # noqa: E501
from endurosat_api.rest import ApiException


class TestSatelliteSubsystemsApi(unittest.TestCase):
    """SatelliteSubsystemsApi unit test stubs"""

    def setUp(self):
        self.api = endurosat_api.api.satellite_subsystems_api.SatelliteSubsystemsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_satellite_subsystem(self):
        """Test case for create_satellite_subsystem

        Create a Satellite Subsystem  # noqa: E501
        """
        pass

    def test_delete_satellite_subsystem_by_id(self):
        """Test case for delete_satellite_subsystem_by_id

        Delete a Satellite Subsystem  # noqa: E501
        """
        pass

    def test_get_filtered_satellite_subsystems(self):
        """Test case for get_filtered_satellite_subsystems

        Get all Satellite Subsystems  # noqa: E501
        """
        pass

    def test_get_satellite_subsystem_by_id(self):
        """Test case for get_satellite_subsystem_by_id

        Get a Satellite Subsystem by ID  # noqa: E501
        """
        pass

    def test_update_satellite_subsystem_by_id(self):
        """Test case for update_satellite_subsystem_by_id

        Update a Satellite Subsystem  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
