# coding: utf-8

"""
    EnduroSat SpaceOps REST API

    Documentation for EnduroSat SpaceOps REST API  # noqa: E501

    The version of the OpenAPI document: 0.34.7
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import endurosat_api
from endurosat_api.api.digital_twin_api import DigitalTwinApi  # noqa: E501
from endurosat_api.rest import ApiException


class TestDigitalTwinApi(unittest.TestCase):
    """DigitalTwinApi unit test stubs"""

    def setUp(self):
        self.api = endurosat_api.api.digital_twin_api.DigitalTwinApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_retrieve_all_simulations(self):
        """Test case for retrieve_all_simulations

        Returns all simulations  # noqa: E501
        """
        pass

    def test_retrieve_simulation_output_files(self):
        """Test case for retrieve_simulation_output_files

        Returns the simulation details including the output files of the simulation  # noqa: E501
        """
        pass

    def test_retrieve_simulation_result_files(self):
        """Test case for retrieve_simulation_result_files

        Returns the simulation result files details  # noqa: E501
        """
        pass

    def test_start_simulation(self):
        """Test case for start_simulation

        Run simulation for a scheduled telecommand  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
