# coding: utf-8

"""
    EnduroSat SpaceOps REST API

    Documentation for EnduroSat SpaceOps REST API  # noqa: E501

    The version of the OpenAPI document: 0.34.7
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import endurosat_api
from endurosat_api.api.events_api import EventsApi  # noqa: E501
from endurosat_api.rest import ApiException


class TestEventsApi(unittest.TestCase):
    """EventsApi unit test stubs"""

    def setUp(self):
        self.api = endurosat_api.api.events_api.EventsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_publish_event(self):
        """Test case for publish_event

        Publish an event  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
