# coding: utf-8

"""
    EnduroSat SpaceOps REST API

    Documentation for EnduroSat SpaceOps REST API  # noqa: E501

    The version of the OpenAPI document: 0.34.7
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import endurosat_api
from endurosat_api.api.satellite_telemetry_api import SatelliteTelemetryApi  # noqa: E501
from endurosat_api.rest import ApiException


class TestSatelliteTelemetryApi(unittest.TestCase):
    """SatelliteTelemetryApi unit test stubs"""

    def setUp(self):
        self.api = endurosat_api.api.satellite_telemetry_api.SatelliteTelemetryApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_filtered_telemetry_entries(self):
        """Test case for get_filtered_telemetry_entries

        Get Historical Telemetry  # noqa: E501
        """
        pass

    def test_get_telemetry_entry_by_id(self):
        """Test case for get_telemetry_entry_by_id

        Get a Satellite Telemetry Entry by ID  # noqa: E501
        """
        pass

    def test_record_batch_telemetry(self):
        """Test case for record_batch_telemetry

        Record Batch Telemetry  # noqa: E501
        """
        pass

    def test_record_telemetry_with_payload(self):
        """Test case for record_telemetry_with_payload

        Record Telemetry with Payload  # noqa: E501
        """
        pass

    def test_update_telemetry_entry_by_id(self):
        """Test case for update_telemetry_entry_by_id

        Update a Telemetry Entry  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
