# coding: utf-8

"""
    EnduroSat SpaceOps REST API

    Documentation for EnduroSat SpaceOps REST API  # noqa: E501

    The version of the OpenAPI document: 0.34.7
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import endurosat_api
from endurosat_api.api.ground_stations_api import GroundStationsApi  # noqa: E501
from endurosat_api.rest import ApiException


class TestGroundStationsApi(unittest.TestCase):
    """GroundStationsApi unit test stubs"""

    def setUp(self):
        self.api = endurosat_api.api.ground_stations_api.GroundStationsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_unavailability_windows_by_ground_station_by_id(self):
        """Test case for add_unavailability_windows_by_ground_station_by_id

        Add an Unavailability Window to a Ground Station  # noqa: E501
        """
        pass

    def test_create_ground_station(self):
        """Test case for create_ground_station

        Create a new Ground Station  # noqa: E501
        """
        pass

    def test_delete_ground_station(self):
        """Test case for delete_ground_station

        Delete a Ground Station by ID  # noqa: E501
        """
        pass

    def test_delete_unavailability_window(self):
        """Test case for delete_unavailability_window

        Delete an Unavailability Window from a Ground Station  # noqa: E501
        """
        pass

    def test_get_all_ground_stations(self):
        """Test case for get_all_ground_stations

        Get all Ground Stations  # noqa: E501
        """
        pass

    def test_get_ground_station_by_id(self):
        """Test case for get_ground_station_by_id

        Get a Ground Station by ID  # noqa: E501
        """
        pass

    def test_get_unavailability_windows_by_ground_station_by_id(self):
        """Test case for get_unavailability_windows_by_ground_station_by_id

        Get all Unavailability Windowss for a Ground Station  # noqa: E501
        """
        pass

    def test_update_ground_station(self):
        """Test case for update_ground_station

        Update a Ground Station  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
