# coding: utf-8

"""
    EnduroSat SpaceOps REST API

    Documentation for EnduroSat SpaceOps REST API  # noqa: E501

    The version of the OpenAPI document: 0.34.7
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import endurosat_api
from endurosat_api.models.telecommand_ground_execution_rules import TelecommandGroundExecutionRules  # noqa: E501
from endurosat_api.rest import ApiException

class TestTelecommandGroundExecutionRules(unittest.TestCase):
    """TelecommandGroundExecutionRules unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test TelecommandGroundExecutionRules
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = endurosat_api.models.telecommand_ground_execution_rules.TelecommandGroundExecutionRules()  # noqa: E501
        if include_optional :
            return TelecommandGroundExecutionRules(
                telecommand_template = '20ec20b5-8535-4593-be85-6fee2a4dd4ba', 
                rules = [
                    endurosat_api.models.execution_rule.ExecutionRule(
                        execution_rule_type = 'SPECIFIC_GROUND_STATION', 
                        properties = {"groundStation":"plana-gs"}, )
                    ]
            )
        else :
            return TelecommandGroundExecutionRules(
        )

    def testTelecommandGroundExecutionRules(self):
        """Test TelecommandGroundExecutionRules"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
