# coding: utf-8

"""
    EnduroSat SpaceOps REST API

    Documentation for EnduroSat SpaceOps REST API  # noqa: E501

    The version of the OpenAPI document: 0.34.7
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import endurosat_api
from endurosat_api.models.user_data_record import UserDataRecord  # noqa: E501
from endurosat_api.rest import ApiException

class TestUserDataRecord(unittest.TestCase):
    """UserDataRecord unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test UserDataRecord
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = endurosat_api.models.user_data_record.UserDataRecord()  # noqa: E501
        if include_optional :
            return UserDataRecord(
                id = '01d11243-af60-46d3-ac8e-d7f4cc3c9104', 
                value = None
            )
        else :
            return UserDataRecord(
        )

    def testUserDataRecord(self):
        """Test UserDataRecord"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
