# coding: utf-8

"""
    EnduroSat SpaceOps REST API

    Documentation for EnduroSat SpaceOps REST API  # noqa: E501

    The version of the OpenAPI document: 0.34.7
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import endurosat_api
from endurosat_api.models.base_conjunction_data import BaseConjunctionData  # noqa: E501
from endurosat_api.rest import ApiException

class TestBaseConjunctionData(unittest.TestCase):
    """BaseConjunctionData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test BaseConjunctionData
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = endurosat_api.models.base_conjunction_data.BaseConjunctionData()  # noqa: E501
        if include_optional :
            return BaseConjunctionData(
                tca = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                miss_distance = 1.337, 
                relative_position_r = 1.337, 
                relative_position_t = 1.337, 
                relative_position_n = 1.337, 
                relative_speed = 1.337, 
                relative_velocity_r = 1.337, 
                relative_velocity_t = 1.337, 
                relative_velocity_n = 1.337, 
                apparent_incidence_angle = 1.337, 
                event_altitude = 1.337, 
                combined_hard_body_radius = 1.337, 
                collision_probability = 1.337, 
                collision_probability_method = 'AKELLAALFRIEND_2000', 
                risk_level = 'LOW', 
                screening_type = 'CAT_VS_CAT', 
                max_scaled_collision_probability = endurosat_api.models.scaled_collision_probability.ScaledCollisionProbability(
                    primary_factor = 1.337, 
                    secondary_factor = 1.337, 
                    probability_of_collision = 1.337, ), 
                is_in_dilution_zone = True
            )
        else :
            return BaseConjunctionData(
        )

    def testBaseConjunctionData(self):
        """Test BaseConjunctionData"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
