# coding: utf-8

"""
    EnduroSat SpaceOps REST API

    Documentation for EnduroSat SpaceOps REST API  # noqa: E501

    The version of the OpenAPI document: 0.34.7
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import endurosat_api
from endurosat_api.models.catalogue_object_with_keplerian_elements import CatalogueObjectWithKeplerianElements  # noqa: E501
from endurosat_api.rest import ApiException

class TestCatalogueObjectWithKeplerianElements(unittest.TestCase):
    """CatalogueObjectWithKeplerianElements unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test CatalogueObjectWithKeplerianElements
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = endurosat_api.models.catalogue_object_with_keplerian_elements.CatalogueObjectWithKeplerianElements()  # noqa: E501
        if include_optional :
            return CatalogueObjectWithKeplerianElements(
                catalogue_id = 56, 
                catalogue_name = '', 
                object_name = '', 
                cospar_id = '', 
                object_type = '', 
                manoeuvrable = 'YES', 
                hard_body_radius = 1.337, 
                orbital_period = 1.337, 
                perigee_altitude = 1.337, 
                apogee_altitude = 1.337, 
                semi_major_axis = 1.337, 
                eccentricity = 1.337, 
                inclination = 1.337, 
                ra_of_asc_node = 1.337, 
                arg_of_pericenter = 1.337, 
                true_anomaly = 1.337, 
                arg_of_latitude = 1.337
            )
        else :
            return CatalogueObjectWithKeplerianElements(
        )

    def testCatalogueObjectWithKeplerianElements(self):
        """Test CatalogueObjectWithKeplerianElements"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
