# coding: utf-8

"""
    EnduroSat SpaceOps REST API

    Documentation for EnduroSat SpaceOps REST API  # noqa: E501

    The version of the OpenAPI document: 0.34.7
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import endurosat_api
from endurosat_api.api.mission_databases_api import MissionDatabasesApi  # noqa: E501
from endurosat_api.rest import ApiException


class TestMissionDatabasesApi(unittest.TestCase):
    """MissionDatabasesApi unit test stubs"""

    def setUp(self):
        self.api = endurosat_api.api.mission_databases_api.MissionDatabasesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_mission_database(self):
        """Test case for create_mission_database

        Create a Mission Database  # noqa: E501
        """
        pass

    def test_create_mission_database_package(self):
        """Test case for create_mission_database_package

        Generate fidl parsers and mission databases from deployment model  # noqa: E501
        """
        pass

    def test_create_procedure_scripts(self):
        """Test case for create_procedure_scripts

        Upload mission database operation script  # noqa: E501
        """
        pass

    def test_delete_mission_database(self):
        """Test case for delete_mission_database

        Delete a MissionDatabase by ID  # noqa: E501
        """
        pass

    def test_delete_mission_database_package(self):
        """Test case for delete_mission_database_package

        Delete all files and mission databases for package  # noqa: E501
        """
        pass

    def test_delete_procedure_scripts(self):
        """Test case for delete_procedure_scripts

        Delete a script for this mission database  # noqa: E501
        """
        pass

    def test_get_filtered_mission_database(self):
        """Test case for get_filtered_mission_database

        Get Mission Databases  # noqa: E501
        """
        pass

    def test_get_mission_database_by_id(self):
        """Test case for get_mission_database_by_id

        Get Mission Database By ID  # noqa: E501
        """
        pass

    def test_get_mission_database_definition(self):
        """Test case for get_mission_database_definition

        Get Mission Database Definition by Mission Database ID  # noqa: E501
        """
        pass

    def test_get_mission_database_packag_by_id(self):
        """Test case for get_mission_database_packag_by_id

        Get mission database package  # noqa: E501
        """
        pass

    def test_get_mission_database_package_source_by_id(self):
        """Test case for get_mission_database_package_source_by_id

        Get fidl package source  # noqa: E501
        """
        pass

    def test_get_mission_database_parser(self):
        """Test case for get_mission_database_parser

        Get URL from which to download Mission Database Fidl Parser by Mission Database ID  # noqa: E501
        """
        pass

    def test_get_mission_database_procedure_script(self):
        """Test case for get_mission_database_procedure_script

        Get Mission Database Procedure by Mission Database ID and Procedure Name  # noqa: E501
        """
        pass

    def test_update_mission_database(self):
        """Test case for update_mission_database

        Update a MissionDatabase  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
