# coding: utf-8

"""
    EnduroSat SpaceOps REST API

    Documentation for EnduroSat SpaceOps REST API  # noqa: E501

    The version of the OpenAPI document: 0.34.7
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import endurosat_api
from endurosat_api.api.payload_files_api import PayloadFilesApi  # noqa: E501
from endurosat_api.rest import ApiException


class TestPayloadFilesApi(unittest.TestCase):
    """PayloadFilesApi unit test stubs"""

    def setUp(self):
        self.api = endurosat_api.api.payload_files_api.PayloadFilesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_finish_multipart_upload(self):
        """Test case for finish_multipart_upload

        Finish multipart upload  # noqa: E501
        """
        pass

    def test_get_download_url(self):
        """Test case for get_download_url

        (DEPRECATED) Get a URL from which to download a file. Use GET /{resourceType}/{resourceId}/artifacts/{artifactType} instead.  # noqa: E501
        """
        pass

    def test_get_download_url1(self):
        """Test case for get_download_url1

        Get a URL from which to download a file  # noqa: E501
        """
        pass

    def test_initiate_multipart_upload(self):
        """Test case for initiate_multipart_upload

        Initiate Multipart Upload  # noqa: E501
        """
        pass

    def test_upload_artifact_file(self):
        """Test case for upload_artifact_file

        Attach payload file to resouce  # noqa: E501
        """
        pass

    def test_upload_file(self):
        """Test case for upload_file

        (DEPRECATED) Attach payload file to resouce. Use PUT /{resourceType}/{resourceId}/artifacts/{artifactType} instead.  # noqa: E501
        """
        pass

    def test_upload_part(self):
        """Test case for upload_part

        Upload Part  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
