# coding: utf-8

"""
    EnduroSat SpaceOps REST API

    Documentation for EnduroSat SpaceOps REST API  # noqa: E501

    The version of the OpenAPI document: 0.34.7
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import endurosat_api
from endurosat_api.models.authentication_response import AuthenticationResponse  # noqa: E501
from endurosat_api.rest import ApiException

class TestAuthenticationResponse(unittest.TestCase):
    """AuthenticationResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test AuthenticationResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = endurosat_api.models.authentication_response.AuthenticationResponse()  # noqa: E501
        if include_optional :
            return AuthenticationResponse(
                access_token = '', 
                expires_in = 56, 
                token_type = '', 
                refresh_token = '', 
                id_token = '', 
                new_device_metadata = endurosat_api.models.new_device_metadata_type.NewDeviceMetadataType(
                    device_key = '', 
                    device_group_key = '', )
            )
        else :
            return AuthenticationResponse(
        )

    def testAuthenticationResponse(self):
        """Test AuthenticationResponse"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
