# coding: utf-8

"""
    EnduroSat SpaceOps REST API

    Documentation for EnduroSat SpaceOps REST API  # noqa: E501

    The version of the OpenAPI document: 0.34.7
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import endurosat_api
from endurosat_api.api.access_control_policy_controller_api import AccessControlPolicyControllerApi  # noqa: E501
from endurosat_api.rest import ApiException


class TestAccessControlPolicyControllerApi(unittest.TestCase):
    """AccessControlPolicyControllerApi unit test stubs"""

    def setUp(self):
        self.api = endurosat_api.api.access_control_policy_controller_api.AccessControlPolicyControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete(self):
        """Test case for delete

        """
        pass

    def test_get_all(self):
        """Test case for get_all

        """
        pass

    def test_get_by_name(self):
        """Test case for get_by_name

        """
        pass

    def test_save(self):
        """Test case for save

        """
        pass

    def test_update(self):
        """Test case for update

        """
        pass


if __name__ == '__main__':
    unittest.main()
