# coding: utf-8

"""
    EnduroSat SpaceOps REST API

    Documentation for EnduroSat SpaceOps REST API  # noqa: E501

    The version of the OpenAPI document: 0.34.7
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import endurosat_api
from endurosat_api.models.satellite_subsystem import SatelliteSubsystem  # noqa: E501
from endurosat_api.rest import ApiException

class TestSatelliteSubsystem(unittest.TestCase):
    """SatelliteSubsystem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test SatelliteSubsystem
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = endurosat_api.models.satellite_subsystem.SatelliteSubsystem()  # noqa: E501
        if include_optional :
            return SatelliteSubsystem(
                id = '01d11243-af60-46d3-ac8e-d7f4cc3c9104', 
                name = 'FLIR Camera', 
                satellite = 'dfcaf59c-0763-4af9-9a65-bd43f7dbf6b0', 
                type = 'camera', 
                configuration = {}
            )
        else :
            return SatelliteSubsystem(
        )

    def testSatelliteSubsystem(self):
        """Test SatelliteSubsystem"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
