# coding: utf-8

"""
    EnduroSat SpaceOps REST API

    Documentation for EnduroSat SpaceOps REST API  # noqa: E501

    The version of the OpenAPI document: 0.34.7
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import endurosat_api
from endurosat_api.api.satellite_passes_api import SatellitePassesApi  # noqa: E501
from endurosat_api.rest import ApiException


class TestSatellitePassesApi(unittest.TestCase):
    """SatellitePassesApi unit test stubs"""

    def setUp(self):
        self.api = endurosat_api.api.satellite_passes_api.SatellitePassesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_cancel_satellite_pass(self):
        """Test case for cancel_satellite_pass

        Cancel a Satellite Pass  # noqa: E501
        """
        pass

    def test_create_satellite_pass(self):
        """Test case for create_satellite_pass

        Book a Satellite Pass  # noqa: E501
        """
        pass

    def test_get_filtered_satellite_passes(self):
        """Test case for get_filtered_satellite_passes

        Get Filtered Satellite Passes  # noqa: E501
        """
        pass

    def test_get_satellite_pass_by_id(self):
        """Test case for get_satellite_pass_by_id

        Get a Satellite Pass by ID  # noqa: E501
        """
        pass

    def test_record_satellite_pass_artifact(self):
        """Test case for record_satellite_pass_artifact

        Record a Satellite Pass Artifact  # noqa: E501
        """
        pass

    def test_record_satellite_pass_log(self):
        """Test case for record_satellite_pass_log

        Record a Satellite Pass Log  # noqa: E501
        """
        pass

    def test_update_satellite_pass_by_id(self):
        """Test case for update_satellite_pass_by_id

        Update a Satellite Pass  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
