# coding: utf-8

"""
    EnduroSat SpaceOps REST API

    Documentation for EnduroSat SpaceOps REST API  # noqa: E501

    The version of the OpenAPI document: 0.34.7
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import endurosat_api
from endurosat_api.models.orbit_config import OrbitConfig  # noqa: E501
from endurosat_api.rest import ApiException

class TestOrbitConfig(unittest.TestCase):
    """OrbitConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test OrbitConfig
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = endurosat_api.models.orbit_config.OrbitConfig()  # noqa: E501
        if include_optional :
            return OrbitConfig(
                start_time = [
                    56
                    ], 
                tp = 56, 
                sma = 56, 
                eccentricity = 1.337, 
                inclination = 1.337, 
                aop = 1.337, 
                raan = 1.337, 
                ltan = 1.337, 
                separation_angle = 1.337, 
                altitude_difference = 1.337, 
                position_error_rtn = [
                    56
                    ]
            )
        else :
            return OrbitConfig(
        )

    def testOrbitConfig(self):
        """Test OrbitConfig"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
