# coding: utf-8

"""
    EnduroSat SpaceOps REST API

    Documentation for EnduroSat SpaceOps REST API  # noqa: E501

    The version of the OpenAPI document: 0.34.7
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import endurosat_api
from endurosat_api.models.simulation_config import SimulationConfig  # noqa: E501
from endurosat_api.rest import ApiException

class TestSimulationConfig(unittest.TestCase):
    """SimulationConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test SimulationConfig
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = endurosat_api.models.simulation_config.SimulationConfig()  # noqa: E501
        if include_optional :
            return SimulationConfig(
                sim_mode = 'ADCS', 
                initial_mode = 'SAFE', 
                number_of_orbits = 56, 
                time_step = 56, 
                max_integration_time_step = 56, 
                start_with_tumbling = True, 
                initial_rate = [
                    1.337
                    ], 
                no_torques = True, 
                no_disturb_torques = True, 
                rw_imbalance_model = 'ADVANCED', 
                stop_on_rw_saturation = True, 
                include_sensor_views = True, 
                include_est_ctrl_compatibility = True, 
                nadir_mode_in_eclipse = True, 
                mode_transition_threshold = 1.337, 
                mode_transition_samples = 56
            )
        else :
            return SimulationConfig(
                sim_mode = 'ADCS',
        )

    def testSimulationConfig(self):
        """Test SimulationConfig"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
